pool:
  vmImage: 'Ubuntu 16.04'

variables:
  APP_NAME: "carts"
  ARTEFACT_ID: "sockshop/$(APP_NAME)"
  ACR_ENDPOINT: $(acrEndpoint)


steps:
- script: |
    versionFromFile=$(cat ./version)
    theTag=$(ACR_ENDPOINT)/$(ARTEFACT_ID)
    theDevTag=$theTag-$versionFromFile-$(Build.BuildId)
    TheStageTag=$theTag-$versionFromFile
    echo "##vso[task.setvariable variable=VERSION]$versionFromFile"
    echo "##vso[task.setvariable variable=TAG]$theTag"
    echo "##vso[task.setvariable variable=TAG_DEV]$theDevTag"
    echo "##vso[task.setvariable variable=TAG_STAGING]$TheStageTag"
  displayName: 'Set build variables'

- script: |
    echo VERSION = $(VERSION)
    echo TAG = $(TAG)
    echo TAG_DEV = $(TAG_DEV)
    echo TAG_STAGING = $(TAG_STAGING)
  displayName: 'Echo build variables values'

- script: |
    sed -i 's#image: .*#image: $(TAG_DEV)#' manifest/$(APP_NAME).yml
    cat manifest/$(APP_NAME).yml
  displayName: 'Update Kubernetes YAML'

- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'

- task: Docker@1
  displayName: 'Login in Azure Container Registry'
  inputs:
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(acrEndpoint)
    command: login

- task: Docker@1
  displayName: 'Build an image on the hosted agent'
  inputs:
   imageName: $(TAG_DEV)

- task: Docker@1
  displayName: 'Push an image to Azure Container Registry'
  inputs:
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(acrEndpoint)
    command: 'Push an image'
    imageName: $(TAG_DEV):latest

- task: PublishBuildArtifacts@1
  displayName: 'Publish Kubernetes YAML'
  inputs:
    pathtoPublish: manifest
    artifactName: manifest

- task: PublishBuildArtifacts@1
  displayName: 'Publish Azure scripts'
  inputs:
    PathtoPublish: azure
    ArtifactName: azure
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Monspec'
  inputs:
    PathtoPublish: monspec
    ArtifactName: monspec

- task: PublishBuildArtifacts@1
  displayName: 'Publish Monspec'
  inputs:
    PathtoPublish: jmeter
    ArtifactName: jmeter

